'solution'
mate-academy/js_get-operands pull request #110
Opened 2020-03-27 15:21 UTC by FaychakA

2020-03-27 16:53 UTC, 8hokage requested changes

2020-03-27 16:53 UTC, earthhuman41 commented on src/getOperands.js
> +  operands = a + operands + b;
думаю можно обойтись без переменных a, b

2020-03-27 16:53 UTC, earthhuman41 commented on src/getOperands.js
> +  let operands = ", ";
это зачем?

2020-03-30 09:28 UTC, denys-cheporniuk approved these changes

2026-01-12 09:56 UTC, closed without merging